baseURL = "https://rohee-katulehti.github.io/"
languageCode = "fi"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

[[menu.header]]
name = "Tule myyjäksi!"
URL = "#myyjaksi"
weight = 2

[[menu.header]]
name = "Ilmoita"
URL = "#ilmoita"
weight = 3

[[menu.header]]
name = "Ota yhteyttä"
URL = "#yhteys"
weight = 4


[[menu.footer]]
name = "Tule myyjäksi!"
URL = "#myyjaksi"
weight = 2

[[menu.footer]]
name = "Ilmoita"
URL = "#ilmoita"
weight = 3

[[menu.footer]]
name = "Ota yhteyttä"
URL = "#yhteys"
weight = 4




[params]

sections = ["home", "about1", "about2", "home2", "contact"]

#googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

[params.logo]
  text1 = "Rohee"
  text2 = "katulehti"

[params.footer]
#    copyright = "© Rohee 2022"
#    [params.footer.radity_logo]
#      x = "img/general/design-and-code-radity.png"
#      _2x = "img/general/design-and-code-radity@2x.png"
#      alt = "Design & Code - Radity"