baseURL = "https://www.rohee.fi/"
languageCode = "fi"
theme = "raditian-free-hugo-theme"

# Plugins
[params.plugins]

# CSS Plugins
[[params.plugins.css]]
URL = "css/main.css"
[[params.plugins.css]]
URL = "css/rad-icons.css"
[[params.plugins.css]]
URL = "css/custom.css"

# JS Plugins
[[params.plugins.js]]
URL = "js/rad-animations.js"
[[params.plugins.js]]
URL = "js/sticky-header.js"
[[params.plugins.js]]
URL = "js/library/fontfaceobserver.js"


# navigation
[menu]

[[menu.header]]
name = "Tule myyjäksi!"
URL = "#myyjaksi"
weight = 2

[[menu.header]]
name = "Ilmoita"
URL = "#ilmoita"
weight = 3

[[menu.header]]
name = "Ota yhteyttä"
URL = "#yhteys"
weight = 4


[[menu.footer]]
name = "Tule myyjäksi!"
URL = "#myyjaksi"
weight = 2

[[menu.footer]]
name = "Ilmoita"
URL = "#ilmoita"
weight = 3

[[menu.footer]]
name = "Ota yhteyttä"
URL = "#yhteys"
weight = 4




[params]

sections = ["home", "about1", "about2", "home2", "contact"]

description = "Rohee on paikallinen katulehti Pirkanmaalla. Katulehteä saa myydä kuka tahansa tuloja tarvitseva. Lehti maksaa kadulla 10 euroa, myyjä on ostanut lehden etukäteen viidellä eurolla ja saa myyntivoiton tuloa. Lehti on innostava ja kiinnostava aikakauslehti täynnä kulttuuria, kokemuksia kaduilta ja yhteiskunnallisia huomioita."
images = ['img/juho-luomala-2wpkWqkPTlY-unsplash.jpg']
title = "Rohee – rouhea ja rohkea tamperelainen katulehti"

#googleTagManagerID = "GTM-000000" # Google Analytics works with Google Tag Manager

[params.logo]
  text1 = "Rohee"
  text2 = "katulehti"

[params.footer]
#    copyright = "© Rohee 2022"
#    [params.footer.radity_logo]
#      x = "img/general/design-and-code-radity.png"
#      _2x = "img/general/design-and-code-radity@2x.png"
#      alt = "Design & Code - Radity"

